export const questions = [
  {
    id: 1,
    question: "What is the capital of Brazil?",
    option1: "Rio de Janeiro",
    option2: "São Paulo",
    option3: "Brasília",
    rightanswer: "option3",
    categories: ["Geography", "History", "PopCulture"],
  },
  {
    id: 2,
    question: "Who wrote 'Don Quixote'?",
    option1: "Miguel de Cervantes",
    option2: "William Shakespeare",
    option3: "Friedrich Nietzsche",
    rightanswer: "option1",
    categories: ["Literature", "History", "Art"],
  },
  {
    id: 3,
    question: "Who painted the 'Mona Lisa'?",
    option1: "Leonardo da Vinci",
    option2: "Pablo Picasso",
    option3: "Vincent van Gogh",
    rightanswer: "option1",
    categories: ["Art", "History", "PopCulture"],
  },
  {
    id: 4,
    question: "What is the largest planet in our solar system?",
    option1: "Earth",
    option2: "Jupiter",
    option3: "Saturn",
    rightanswer: "option2",
    categories: ["Science"],
  },
  {
    id: 5,
    question: "Which element has the chemical symbol 'O'?",
    option1: "Gold",
    option2: "Oxygen",
    option3: "Osmium",
    rightanswer: "option2",
    categories: ["Science"],
  },
  {
    id: 6,
    question: "What is the capital of France?",
    option1: "Rome",
    option2: "Berlin",
    option3: "Paris",
    rightanswer: "option3",
    categories: ["Geography", "History"],
  },
  {
    id: 7,
    question: "Who is known as the 'Father of Computers'?",
    option1: "Alan Turing",
    option2: "Charles Babbage",
    option3: "Bill Gates",
    rightanswer: "option2",
    categories: ["Technology", "History"],
  },
  {
    id: 8,
    question: "In which year did the Titanic sink?",
    option1: "1912",
    option2: "1914",
    option3: "1916",
    rightanswer: "option1",
    categories: ["History"],
  },
  {
    id: 9,
    question: "What is the tallest mountain in the world?",
    option1: "K2",
    option2: "Kangchenjunga",
    option3: "Mount Everest",
    rightanswer: "option3",
    categories: ["Geography", "Nature"],
  },
  {
    id: 10,
    question: "Who developed the theory of relativity?",
    option1: "Isaac Newton",
    option2: "Albert Einstein",
    option3: "Galileo Galilei",
    rightanswer: "option2",
    categories: ["Science"],
  },
  {
    id: 11,
    question: "What is the smallest prime number?",
    option1: "0",
    option2: "1",
    option3: "2",
    rightanswer: "option3",
    categories: ["Mathematics"],
  },
  {
    id: 12,
    question: "Who is the author of 'Harry Potter' series?",
    option1: "J.R.R. Tolkien",
    option2: "J.K. Rowling",
    option3: "George R.R. Martin",
    rightanswer: "option2",
    categories: ["Literature", "PopCulture"],
  },
];
